### ISSUE TITLE
Update scoring algorithm for deprecated resources

### ISSUE THREAD

**Issue by mbdebian** [identifiers-org/cloud-ws-resource-recommender#12]
Those resources part of the resolver output that are deprecated, should be given the lowest recommendation score straight away, to make sure they're the last ones down the list of resolved providers.

**Comment by mbdebian** [comment]
I've just updated the scoring algorithm to only score not deprecated resources in not deprecated namespaces

**Comment by renatocjn** [comment]
This is working well. Deprecated entities are evaluated to zero.
